### ISSUE TITLE
CMake finds system installs of boost instead of the one in vital_DIR

### ISSUE THREAD

**Issue by bastienjacquet** [Kitware/TeleSculptor#128]
If running cmake with providing the vital_DIR, cmake still finds the system-wide Boost install.
I'm not a cmake-expert, so it might just be expected.

```
cmake ../maptk/ -Dvital_DIR:FILEPATH=/home/bjacquet/Dev/MAP-Tk/Vital/build
```

btw, it is annoying because maptk does not compile against Boost 1.58.0, which is the default on Ubuntu 15.10. But this is another issue.

**Comment by mleotta** [comment]
Thanks for reporting this.  The behavior is probably is expected from the CMake point of view, but we can still make this easier.  Either we should add a "fletch_DIR" option directly to MAP-Tk or inherit this from Vital.  Either way, MAP-Tk should look for fletch builds before system builds.

Regarding the second issue.  I agree that MAP-Tk should be fixed to allow building against system versions of libraries from current versions of Ubuntu or at least long-term support (LTS) versions.  It does currently support Ubuntu 14.04 LTS, but very shortly we will have Ubuntu 16.04 LTS and we should support that too.  However, in the specific case of Boost, the better solution is to just remove the Boost dependency entirely.  When [Vital](https://github.com/kitware/vital) was refactored out of MAP-Tk we made a decision to move to C++11.  This allowed us to replace 90% of our Boost dependencies with the standard library.  In Vital we removed Boost entirely by replacing the remaining usage with functionality from KWSys (now included in Vital).  We should be able to do the same in MAP-Tk. 

Both of these changes would be good for @linus-sherrill to look at.

**Comment by Purg** [comment]
According to the [CMake docs here](https://cmake.org/cmake/help/v3.4/command/set.html), the ``FILEPATH`` is supposed to reference a specific file, not a directory, so CMake might be getting confused here. Have you tried using ``PATH`` instead?

Another boost magic CMake variable is ``BOOST_ROOT`` which should be set to the install root directory (meaning the ``PATH`` type should be used) where to pick up a specific boost install.

**Comment by bastienjacquet** [comment]
I'm getting the same behavior using `PATH` instead.
MAP-Tk compiles fine if I manually change all Boost paths to the Fletch install.

However, I get the same problem if I activate OpenCV, or QT (with the GUI): The system installs are found first. For QT, it means correcting 200+ QT_* cmake variables ... :(

**Comment by mleotta** [comment]
Yes, at most your should have to manually set one or two paths manually for each dependency, which one you need to set depends on the library.

Either way, we need to make this easier to use with fletch.

**Comment by mleotta** [comment]
This is an old issue which has hopefully been resolved with the introduction of the super build.  I'm going to close it, but feel free to re-open if there are still issues.
