### ISSUE TITLE
error:the file"kwiver_algo_core_export.h" is missing

### ISSUE THREAD

**Issue by calman1314** [Kitware/TeleSculptor#234]
"*/arrow/core/kwiver_algo_core_export.h: no such file ...",the error is arising,when I building the maptk/tools/analyze_tracks.cxx. And I found that no file named "kwiver_algo_core_export.h" is in the folder of  map-tk or kitware.

**Comment by mleotta** [comment]
This is an old issue.  I'm closing it, but you can reopen if there are still issues.  Note that the `*_export.h` files are generated headers and are found in the build tree.
