### ISSUE TITLE
maptk_bundle_adjust_tracks exception thrown with kwiver_wami dataset

### ISSUE THREAD

**Issue by mmonroe-iai** [Kitware/TeleSculptor#264]
Hello,
I am using commit 26c3a2ca3fbbaa0cde94dcacdd0529178985eb33 of the master branch (with an added fix to properly write out the tracks.txt file in track_features.cxx).

An exception is thrown when running maptk_bundle_adjust_tracks on the example dataset kwiver_wami_set_1 (Exception caught: _Map_base::at). It looks like the exception occurs when it tries to set the local origin while initializing the cameras with metadata. Here is a rough trace to the exception: 
Bundle_adjust_tracks.cxx:604 (maptk_main) -> bundle_adjust_tracks.cxx:382 (load_input_cameras) -> local_geo_cs.cxx:211 (initialize_cameras_with_metadata) -> local_geo_cs.cxx:82 (set_origin)

Here are the last few lines of output before the exception occurred: 
2017-08-22 08:10:16.608 DEBUG config_block_io.cxx(307): Read config file "./maptk_bundle_adjust_tracks.conf"
2017-08-22 08:10:16.747 INFO bundle_adjust_tracks.cxx(514): loading track file: results/tracks.txt
2017-08-22 08:10:31.355 DEBUG bundle_adjust_tracks.cxx(517): loaded 104869 tracks
2017-08-22 08:10:39.903 DEBUG bundle_adjust_tracks.cxx(531): filtered down to 5449 long tracks
track filtering - elapsed time: 8.64224 sec
2017-08-22 08:10:40.12 INFO bundle_adjust_tracks.cxx(558): Reading Video
2017-08-22 08:10:40.771 ERROR bundle_adjust_tracks.cxx(911): Exception caught: _Map_base::at

Thanks in advance for any help fixing this issue!

**Comment by mleotta** [comment]
Thanks for reporting.  I'll try to reproduce it.  What OS are you using?

**Comment by mmonroe-iai** [comment]
I am using Ubuntu 16.04.3.

**Comment by mmonroe-iai** [comment]
I am also having issues running maptk_bundle_adjust_tracks on kwiver_fmv_set_1 if this gives you any more insight as to what the overall problem may be. Most of the bundle adjustment runs, but all of the data is filled with 0 and NaN values. The root of the issue seems to occur when initializing the cameras and landmarks. 

Here is a rough trace to where I first notice the NaN values:
Bundle_adjust_tracks.cxx:723 (maptk_main) -> kwiver::arrows::core::initialize_cameras_landmarks.cxx:1075 (initialize) -> kwiver::vital::algo::optimize_cameras.cxx:131 (optimize) -> kwiver::arrows::vxl::optimize_cameras.cxx:135 (optimize) -> kwiver::arrows::vxl::optimize_cameras.cxx:84 (opt_orient_pos) 

After lm.minimize is called at kwiver::arrows::vxl::optimize_cameras.cxx:84, the rotation vector goes from <0,0,0> to <NaN,NaN,NaN> and the camera center goes from <0,0,-1> to <NaN,NaN,NaN>.
This may be an issue with Kwiver or VXL and not MAP-Tk, but I figured I would list it here in case it gives you any insight into the issue above. Thanks again!

**Comment by mmonroe-iai** [comment]
I've looked into this issue a bit more. When it tries to extract the origin from the metadata into the geo_point object gloc (at local_geo_cs.cxx:115) there is a type mismatch. The metadata origin is of type geo_lat_lon and not of type geo_point as expected. Because the types do not match (at kwiver/vital/video_metadata/video_metadata.h:129) the geo_point is not initialized with the latitude and longitude extracted from the metadata. Eventually this uninitialized geo_point causes the exception to be thrown.

**Comment by mleotta** [comment]
Thanks for looking into this, that information helps a lot.  I haven't had time to address this but I will soon.  It sounds like this problem is due to a recent change in KWIVER that is restructuring the way we deal with geographic data structures and conversions.  KWIVER has a PR (Kitware/kwiver#241) to remove the old data structures (e.g. geo_lat_lon) that will probably fix this.  In the mean time you could either try using the commit from that PR in KWIVER or use the `release` branches of Fletch/KWIVER/MAP-Tk together.

**Comment by mmonroe-iai** [comment]
Thanks Matt. I will switch over to using the release branches for now.

**Comment by mleotta** [comment]
This is an old issue that should be resolved.  I'm closing it, but you can re-open if needed.
