### ISSUE TITLE
Qt version 5.11.2 cannot be downloaded

### ISSUE THREAD

**Issue by P-mind** [Kitware/TeleSculptor#337]
After running 'make' I get the following error
>          --- LOG END ---
>         error: downloading 'http://download.qt->project.org/official_releases/qt/5.11/5.11.2/single/qt-everywhere-src-5.11.2.tar.xz' failed
>         status_code: 22
>         status_string: "HTTP response code said error"
>         log:
>         --- LOG BEGIN ---
>           Trying 77.86.229.90:80...

It seems like that Qt version 5.11.2 cannot be found on: http://download.qt-project.org/official_releases/qt/ 
Can you please update the Qt version to the newest versions are 5.12 or 5.13

Thanks a lot.

**Comment by mleotta** [comment]
Shortly after we made the v1.0.0 release Qt removed the 5.11.2 download link that Fletch was using.  We are updating to Qt 5.12 in Fletch and will get TeleSculptor updated to use this soon.  See also https://github.com/Kitware/fletch/pull/538

**Comment by mleotta** [comment]
There are some issues holding up Qt 5.12, but in the mean time you could try PR #338 that updates Fletch with fixes to the download URL for Qt 5.11.  

Note that the CI issues on that PR are unrelated.  Travis CI uses a nightly pre-built Fletch to save time, so it does not test this change.

**Comment by mleotta** [comment]
This has been resolved in the `master` and `release` branches by updating Fletch in #338.  We have not updated to Qt 5.12 yet, but the URL for Qt 5.11 is fixed.
