### ISSUE TITLE
first calibrated camera visibility

### ISSUE THREAD

**Issue by borovik135** [Kitware/TeleSculptor#458]
Open/create a project that does not have cameras in TS GUI. Ensure a scene mesh is loaded. Pick a frame and calibrate a camera for it using six 3D-2D point correspondences. Observe the log for a successful calibration and a view re-projection on the mesh. Although camera is calibrated and inserted it is not visible in the 3D viewer. Calibrate a camera for a different frame, and observe that now two camera frustums are visible in the 3D viewer. The idea is to display the first calibrated camera frustum without having to calibrate any additional ones.

**Comment by mwoehlke-kitware** [comment]
Okay, I can reproduce. I don't see any reason why this should be a matter of simply failing to repaint. On further consideration, I suspect this is a fundamental problem of the camera representation; specifically, it is simply not capable of displaying a single camera (possibly related to the expectation of having a path).

To be clear, when I say "not capable", I don't mean I think this is intractable, just that the code in its current state expects multiple cameras and likely has checks in place to do nothing if it doesn't. (IOW, it's not just something trivial like not issuing an update.)

**Comment by mwoehlke-kitware** [comment]
So... after staring at this for a while, I still have no clue *why* it's happening... However, commenting out the code to update the path fixes the issue. So it seems there definitely *is* an issue somehow with the path having too few points.

**Comment by mleotta** [comment]
So... does that mean we could add a conditional?  If number of cameras > 1 run code that needs to be commented out otherwise skip it?

**Comment by mleotta** [comment]
Well, If a path is not defined for only one camera then I don't see why it is kludgy to skip the case of updating an undefined path, but I may not have to full context here.  Can you provide a link to the code you commented out to make this work?

**Comment by mwoehlke-kitware** [comment]
Why does an "issue" with the *path actor* cause the *active camera actor* to not render? It doesn't seem like those should be connected in any way.
