### ISSUE TITLE
clear GCP/reg.pt list on project (re)load

### ISSUE THREAD

**Issue by borovik135** [Kitware/TeleSculptor#473]
Load project A with a mesh, inspect/create some GCP and registration points, compute cameras, export GCP points. Without closing TS, open project B with a mesh and GCP/reg.pts: now GCP and reg pts from two projects appear to be intermixed. I think we need to clear our GCP list on project (re) load.

**Comment by mleotta** [comment]
There are probably various other things that need to be cleared as well.  We've never really put effort into supporting closing one project and opening another without closing the app.  For now I suggest you avoid opening multiple projects in a single session.

**Comment by mleotta** [comment]
You could open a more general issue to "support closing a project and loading a different one without restarting TeleSculptor" if you want.  But I don't think we'll address that in the short term.
