### ISSUE TITLE
Patch release with CPU-only depth map computation

### ISSUE THREAD

**Issue by russelldj** [Kitware/TeleSculptor#495]
I tried to run the Linux `1.1.2` release and it looks like it still requires a CUDA GPU for depth integration, though I thought a CPU-only version landed in KWIVER. I think that functionality could be very useful to people and might warrant a release.

**Comment by mleotta** [comment]
It will be in the next release.  However, we have not yet written the code to automatically enable it if you don't have a CUDA-enabled GPU or add a GUI switch to enable/disable GPU.  You will need to manual turn it on in a config file.

**Comment by mleotta** [comment]
addressed by #522
