### ISSUE TITLE
running from docker image

### ISSUE THREAD

**Issue by rezural** [Kitware/TeleSculptor#507]
I'm trying to get telesculpter working on ubuntu 20.04, within the docker image.

docker build works fine, but then docker run doesnt actually run anything. Is there something I am missing to getting the telesculptor UI running?

**Comment by mleotta** [comment]
Are you referring to the KWIVER docker container?  I don't believe TeleSculptor has a docker container.  However, TeleSculptor is a GUI that builds on KWIVER and all the algorithms are in KWIVER.  So you can run a series of KWIVER command line calls in docker to run the same algorithms as the TeleSculptor GUI, but no GUI in docker.  My understanding is that docker is not a good option for distributing GUIs, but I may be wrong.

**Comment by mleotta** [comment]
I overlooked something in my last comment.  There is a `Dockerfile` in TeleSculptor, but that is currently used to create a clean build environment for packaging TeleSculptor.  Once the Docker container builds the installer package we extract that package and distribute it for use on native Linux systems.  It may be possible to run TeleSculptor in that Docker image, but I don't know much about running graphical applications from within Docker.  If you know how to do that may you can contribute a change that sets up the Docker container to allow running the UI.
